name: push-to-prod.yaml
on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get PR Number
        id: timestamp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUM=$(gh pr list --search '${{github.sha}}' -s all --json number -q '.[] | .number' || echo "latest")
          TIMESTAMP=$(printf '%(%Y.%m.%d.%H%M%S)T\n' -1)
          echo "container-tag=$PR_NUM.$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags:
            - ghcr.io/terramagma/terrastack-docs:latest
            - ghcr.io/terramagma/terrastack-docs:${{ steps.timestamp.outputs.container-tag }}

